AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  notify-web-update
  
  Sample SAM Template for notify-web-update

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5
    MemorySize: 128
    Environment:
       Variables:
          LINE_NOTIFY_TOKEN: !Sub '${LINE_NOTIFY_TOKEN}'

Resources:
  NotifyWebUpdateFunction: # Function名をあなたのプロジェクト名に変更
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src # ディレクトリ名をあなたのプロジェクト名に変更
      Handler: notify-web-update # ハンドラ名をあなたのプロジェクト名に変更
      Runtime: go1.x
      Events:
        HelloWorld:
          Type: Api 
          Properties:
            Path: /notify
            Method: get


Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldAPI:
    Description: "API Gateway endpoint URL for Prod environment for First Function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "First Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
